#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

components-$(CONFIG_APP_SIDE_BENCH)        += side-bench
side-bench: common libsel4 libmuslc libsel4vka libcpio libelf \
                                             libsel4allocman \
        libplatsupport libsel4platsupport libsel4muslcsys libsel4test \
         libsel4simple libsel4vspace libsel4utils libutils \
         libsel4cachecolor libsel4bench libsel4simple-stable 

