#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

# Targets                                                                  
TARGETS := $(notdir $(SOURCE_DIR)).bin

# Set custom entry point as we are a rootserver and will not be            
# started in a standard way
ENTRY_POINT := _sel4_start

# Source files required to build the target                                
CFILES   := $(patsubst $(SOURCE_DIR)/%,%,$(wildcard $(SOURCE_DIR)/src/*.c))

# CPIO archive                                                             
OFILES := archive.o                                                        

# Libraries required to build the target                                   
LIBS = c sel4 cpio elf sel4muslcsys sel4vka sel4allocman \
platsupport sel4platsupport sel4vspace \
sel4utils sel4debug sel4simple utils sel4bench                       


ifdef CONFIG_KERNEL_STABLE 
LIBS += sel4simple-stable 
else 
LIBS += sel4simple-default 
endif

ifdef CONFIG_LIB_SEL4_CACHECOLOURING
LIBS += sel4cachecolour
endif 


# extra cflag for manager
CFLAGS += -Werror -g -Wno-unused-function
ifdef CONFIG_X86_64
CFLAGS += -mno-sse
endif

include $(SEL4_COMMON)/common.mk

# targets to generate CPIO archive of elf files
${COMPONENTS}:
	false

archive.o: ${COMPONENTS}
	$(Q)mkdir -p $(dir $@)
	${COMMON_PATH}/files_to_obj.sh $@ _cpio_archive $^


